<?php

use Drupal\hsbxl_members\Entity\Membership;
use Drupal\hsbxl_members\MembershipService;
use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_entity_insert().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function hsbxl_members_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  $config = \Drupal::config('hsbxl_members.settings');
  $membershipService = \Drupal::service('hsbxl_members.membership');

  // If the bundle is a bankstatement,
  // check if it was a membership payment.
  if ($entity->bundle() == 'bankstatement') {

    $amount = $entity->get('field_booking_amount')->getValue()[0]['value'];
    $memo = $entity->get('field_bankstatement_memo')->getValue()[0]['value'];

    if($amount > 0) {
      $membershipService->setStructuredMemo($memo);
      $membershipService->processMembershipFee($amount);
    }
  }
}